/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DesignationsRouteImport } from './routes/designations'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as AttendanceQrRouteImport } from './routes/attendance.qr'

const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignationsRoute = DesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const AttendanceQrRoute = AttendanceQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AttendanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/sites': typeof SitesRoute
  '/attendance/qr': typeof AttendanceQrRoute
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/sites': typeof SitesRoute
  '/attendance/qr': typeof AttendanceQrRoute
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/sites': typeof SitesRoute
  '/attendance/qr': typeof AttendanceQrRoute
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/auth'
    | '/branches'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/entities'
    | '/sites'
    | '/attendance/qr'
    | '/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/auth'
    | '/branches'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/entities'
    | '/sites'
    | '/attendance/qr'
    | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/auth'
    | '/branches'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/entities'
    | '/sites'
    | '/attendance/qr'
    | '/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRouteWithChildren
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DesignationsRoute: typeof DesignationsRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  EntitiesRoute: typeof EntitiesRoute
  SitesRoute: typeof SitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designations': {
      id: '/designations'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof DesignationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/attendance/qr': {
      id: '/attendance/qr'
      path: '/qr'
      fullPath: '/attendance/qr'
      preLoaderRoute: typeof AttendanceQrRouteImport
      parentRoute: typeof AttendanceRoute
    }
  }
}

interface AttendanceRouteChildren {
  AttendanceQrRoute: typeof AttendanceQrRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceQrRoute: AttendanceQrRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRouteWithChildren,
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  DepartmentsRoute: DepartmentsRoute,
  DesignationsRoute: DesignationsRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  EntitiesRoute: EntitiesRoute,
  SitesRoute: SitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
