/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminSitesRouteImport } from './routes/superadmin-sites'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin-dashboard'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReimbursementsRouteImport } from './routes/reimbursements'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OfferTemplatesRouteImport } from './routes/offer-templates'
import { Route as OfferLettersRouteImport } from './routes/offer-letters'
import { Route as MyCalendarRouteImport } from './routes/my-calendar'
import { Route as ManageRequestsRouteImport } from './routes/manage-requests'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LeaveInboxRouteImport } from './routes/leave-inbox'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmployeeSeparationRouteImport } from './routes/employee-separation'
import { Route as DesignationsRouteImport } from './routes/designations'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BillingPaymentsRouteImport } from './routes/billing-payments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AllOffersRouteImport } from './routes/all-offers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as HolidaysIndexRouteImport } from './routes/holidays.index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance.index'
import { Route as PayrollStructureRouteImport } from './routes/payroll.structure'
import { Route as PayrollSlipsRouteImport } from './routes/payroll.slips'
import { Route as PayrollRunRouteImport } from './routes/payroll.run'
import { Route as PayrollImportCtcRouteImport } from './routes/payroll.import-ctc'
import { Route as PayrollComplianceRouteImport } from './routes/payroll.compliance'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations.$orgId'
import { Route as InsightsOrgTreeRouteImport } from './routes/insights.org-tree'
import { Route as HolidaysCalendarRouteImport } from './routes/holidays.calendar'
import { Route as Form16MyRouteImport } from './routes/form-16.my'
import { Route as Form16ManagementRouteImport } from './routes/form-16.management'
import { Route as Form16BulkRouteImport } from './routes/form-16.bulk'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as BillingPaymentsOrgIdRouteImport } from './routes/billing-payments.$orgId'
import { Route as AttendanceShiftsRouteImport } from './routes/attendance.shifts'
import { Route as AttendanceRosterRouteImport } from './routes/attendance.roster'
import { Route as AttendanceRegularizeRouteImport } from './routes/attendance.regularize'
import { Route as AttendanceQrRouteImport } from './routes/attendance.qr'
import { Route as AttendanceGpsRouteImport } from './routes/attendance.gps'
import { Route as AttendanceFaceRouteImport } from './routes/attendance.face'

const SuperadminSitesRoute = SuperadminSitesRouteImport.update({
  id: '/superadmin-sites',
  path: '/superadmin-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin-dashboard',
  path: '/superadmin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReimbursementsRoute = ReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferTemplatesRoute = OfferTemplatesRouteImport.update({
  id: '/offer-templates',
  path: '/offer-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferLettersRoute = OfferLettersRouteImport.update({
  id: '/offer-letters',
  path: '/offer-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCalendarRoute = MyCalendarRouteImport.update({
  id: '/my-calendar',
  path: '/my-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRequestsRoute = ManageRequestsRouteImport.update({
  id: '/manage-requests',
  path: '/manage-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveInboxRoute = LeaveInboxRouteImport.update({
  id: '/leave-inbox',
  path: '/leave-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSeparationRoute = EmployeeSeparationRouteImport.update({
  id: '/employee-separation',
  path: '/employee-separation',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignationsRoute = DesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPaymentsRoute = BillingPaymentsRouteImport.update({
  id: '/billing-payments',
  path: '/billing-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AllOffersRoute = AllOffersRouteImport.update({
  id: '/all-offers',
  path: '/all-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRoute,
} as any)
const HolidaysIndexRoute = HolidaysIndexRouteImport.update({
  id: '/holidays/',
  path: '/holidays/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendanceRoute,
} as any)
const PayrollStructureRoute = PayrollStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollSlipsRoute = PayrollSlipsRouteImport.update({
  id: '/slips',
  path: '/slips',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollRunRoute = PayrollRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollImportCtcRoute = PayrollImportCtcRouteImport.update({
  id: '/import-ctc',
  path: '/import-ctc',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollComplianceRoute = PayrollComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PayrollRoute,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrganizationsRoute,
} as any)
const InsightsOrgTreeRoute = InsightsOrgTreeRouteImport.update({
  id: '/insights/org-tree',
  path: '/insights/org-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysCalendarRoute = HolidaysCalendarRouteImport.update({
  id: '/holidays/calendar',
  path: '/holidays/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const Form16MyRoute = Form16MyRouteImport.update({
  id: '/form-16/my',
  path: '/form-16/my',
  getParentRoute: () => rootRouteImport,
} as any)
const Form16ManagementRoute = Form16ManagementRouteImport.update({
  id: '/form-16/management',
  path: '/form-16/management',
  getParentRoute: () => rootRouteImport,
} as any)
const Form16BulkRoute = Form16BulkRouteImport.update({
  id: '/form-16/bulk',
  path: '/form-16/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const BillingPaymentsOrgIdRoute = BillingPaymentsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => BillingPaymentsRoute,
} as any)
const AttendanceShiftsRoute = AttendanceShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceRosterRoute = AttendanceRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceRegularizeRoute = AttendanceRegularizeRouteImport.update({
  id: '/regularize',
  path: '/regularize',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceQrRoute = AttendanceQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceGpsRoute = AttendanceGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceFaceRoute = AttendanceFaceRouteImport.update({
  id: '/face',
  path: '/face',
  getParentRoute: () => AttendanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-offers': typeof AllOffersRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing-payments': typeof BillingPaymentsRouteWithChildren
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employee-separation': typeof EmployeeSeparationRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/leave': typeof LeaveRoute
  '/leave-inbox': typeof LeaveInboxRoute
  '/loans': typeof LoansRoute
  '/manage-requests': typeof ManageRequestsRoute
  '/my-calendar': typeof MyCalendarRoute
  '/offer-letters': typeof OfferLettersRoute
  '/offer-templates': typeof OfferTemplatesRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/payroll': typeof PayrollRouteWithChildren
  '/reimbursements': typeof ReimbursementsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/superadmin-dashboard': typeof SuperadminDashboardRoute
  '/superadmin-sites': typeof SuperadminSitesRoute
  '/attendance/face': typeof AttendanceFaceRoute
  '/attendance/gps': typeof AttendanceGpsRoute
  '/attendance/qr': typeof AttendanceQrRoute
  '/attendance/regularize': typeof AttendanceRegularizeRoute
  '/attendance/roster': typeof AttendanceRosterRoute
  '/attendance/shifts': typeof AttendanceShiftsRoute
  '/billing-payments/$orgId': typeof BillingPaymentsOrgIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/form-16/bulk': typeof Form16BulkRoute
  '/form-16/management': typeof Form16ManagementRoute
  '/form-16/my': typeof Form16MyRoute
  '/holidays/calendar': typeof HolidaysCalendarRoute
  '/insights/org-tree': typeof InsightsOrgTreeRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/payroll/compliance': typeof PayrollComplianceRoute
  '/payroll/import-ctc': typeof PayrollImportCtcRoute
  '/payroll/run': typeof PayrollRunRoute
  '/payroll/slips': typeof PayrollSlipsRoute
  '/payroll/structure': typeof PayrollStructureRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/holidays/': typeof HolidaysIndexRoute
  '/payroll/': typeof PayrollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-offers': typeof AllOffersRoute
  '/auth': typeof AuthRoute
  '/billing-payments': typeof BillingPaymentsRouteWithChildren
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employee-separation': typeof EmployeeSeparationRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/leave': typeof LeaveRoute
  '/leave-inbox': typeof LeaveInboxRoute
  '/loans': typeof LoansRoute
  '/manage-requests': typeof ManageRequestsRoute
  '/my-calendar': typeof MyCalendarRoute
  '/offer-letters': typeof OfferLettersRoute
  '/offer-templates': typeof OfferTemplatesRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/reimbursements': typeof ReimbursementsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/superadmin-dashboard': typeof SuperadminDashboardRoute
  '/superadmin-sites': typeof SuperadminSitesRoute
  '/attendance/face': typeof AttendanceFaceRoute
  '/attendance/gps': typeof AttendanceGpsRoute
  '/attendance/qr': typeof AttendanceQrRoute
  '/attendance/regularize': typeof AttendanceRegularizeRoute
  '/attendance/roster': typeof AttendanceRosterRoute
  '/attendance/shifts': typeof AttendanceShiftsRoute
  '/billing-payments/$orgId': typeof BillingPaymentsOrgIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/form-16/bulk': typeof Form16BulkRoute
  '/form-16/management': typeof Form16ManagementRoute
  '/form-16/my': typeof Form16MyRoute
  '/holidays/calendar': typeof HolidaysCalendarRoute
  '/insights/org-tree': typeof InsightsOrgTreeRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/payroll/compliance': typeof PayrollComplianceRoute
  '/payroll/import-ctc': typeof PayrollImportCtcRoute
  '/payroll/run': typeof PayrollRunRoute
  '/payroll/slips': typeof PayrollSlipsRoute
  '/payroll/structure': typeof PayrollStructureRoute
  '/attendance': typeof AttendanceIndexRoute
  '/holidays': typeof HolidaysIndexRoute
  '/payroll': typeof PayrollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-offers': typeof AllOffersRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing-payments': typeof BillingPaymentsRouteWithChildren
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employee-separation': typeof EmployeeSeparationRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/leave': typeof LeaveRoute
  '/leave-inbox': typeof LeaveInboxRoute
  '/loans': typeof LoansRoute
  '/manage-requests': typeof ManageRequestsRoute
  '/my-calendar': typeof MyCalendarRoute
  '/offer-letters': typeof OfferLettersRoute
  '/offer-templates': typeof OfferTemplatesRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/payroll': typeof PayrollRouteWithChildren
  '/reimbursements': typeof ReimbursementsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/superadmin-dashboard': typeof SuperadminDashboardRoute
  '/superadmin-sites': typeof SuperadminSitesRoute
  '/attendance/face': typeof AttendanceFaceRoute
  '/attendance/gps': typeof AttendanceGpsRoute
  '/attendance/qr': typeof AttendanceQrRoute
  '/attendance/regularize': typeof AttendanceRegularizeRoute
  '/attendance/roster': typeof AttendanceRosterRoute
  '/attendance/shifts': typeof AttendanceShiftsRoute
  '/billing-payments/$orgId': typeof BillingPaymentsOrgIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/form-16/bulk': typeof Form16BulkRoute
  '/form-16/management': typeof Form16ManagementRoute
  '/form-16/my': typeof Form16MyRoute
  '/holidays/calendar': typeof HolidaysCalendarRoute
  '/insights/org-tree': typeof InsightsOrgTreeRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/payroll/compliance': typeof PayrollComplianceRoute
  '/payroll/import-ctc': typeof PayrollImportCtcRoute
  '/payroll/run': typeof PayrollRunRoute
  '/payroll/slips': typeof PayrollSlipsRoute
  '/payroll/structure': typeof PayrollStructureRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/holidays/': typeof HolidaysIndexRoute
  '/payroll/': typeof PayrollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-offers'
    | '/attendance'
    | '/auth'
    | '/billing-payments'
    | '/branches'
    | '/departments'
    | '/designations'
    | '/employee-separation'
    | '/employees'
    | '/entities'
    | '/leave'
    | '/leave-inbox'
    | '/loans'
    | '/manage-requests'
    | '/my-calendar'
    | '/offer-letters'
    | '/offer-templates'
    | '/organizations'
    | '/payroll'
    | '/reimbursements'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/superadmin-dashboard'
    | '/superadmin-sites'
    | '/attendance/face'
    | '/attendance/gps'
    | '/attendance/qr'
    | '/attendance/regularize'
    | '/attendance/roster'
    | '/attendance/shifts'
    | '/billing-payments/$orgId'
    | '/employees/$id'
    | '/form-16/bulk'
    | '/form-16/management'
    | '/form-16/my'
    | '/holidays/calendar'
    | '/insights/org-tree'
    | '/organizations/$orgId'
    | '/payroll/compliance'
    | '/payroll/import-ctc'
    | '/payroll/run'
    | '/payroll/slips'
    | '/payroll/structure'
    | '/attendance/'
    | '/holidays/'
    | '/payroll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-offers'
    | '/auth'
    | '/billing-payments'
    | '/branches'
    | '/departments'
    | '/designations'
    | '/employee-separation'
    | '/employees'
    | '/entities'
    | '/leave'
    | '/leave-inbox'
    | '/loans'
    | '/manage-requests'
    | '/my-calendar'
    | '/offer-letters'
    | '/offer-templates'
    | '/organizations'
    | '/reimbursements'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/superadmin-dashboard'
    | '/superadmin-sites'
    | '/attendance/face'
    | '/attendance/gps'
    | '/attendance/qr'
    | '/attendance/regularize'
    | '/attendance/roster'
    | '/attendance/shifts'
    | '/billing-payments/$orgId'
    | '/employees/$id'
    | '/form-16/bulk'
    | '/form-16/management'
    | '/form-16/my'
    | '/holidays/calendar'
    | '/insights/org-tree'
    | '/organizations/$orgId'
    | '/payroll/compliance'
    | '/payroll/import-ctc'
    | '/payroll/run'
    | '/payroll/slips'
    | '/payroll/structure'
    | '/attendance'
    | '/holidays'
    | '/payroll'
  id:
    | '__root__'
    | '/'
    | '/all-offers'
    | '/attendance'
    | '/auth'
    | '/billing-payments'
    | '/branches'
    | '/departments'
    | '/designations'
    | '/employee-separation'
    | '/employees'
    | '/entities'
    | '/leave'
    | '/leave-inbox'
    | '/loans'
    | '/manage-requests'
    | '/my-calendar'
    | '/offer-letters'
    | '/offer-templates'
    | '/organizations'
    | '/payroll'
    | '/reimbursements'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/superadmin-dashboard'
    | '/superadmin-sites'
    | '/attendance/face'
    | '/attendance/gps'
    | '/attendance/qr'
    | '/attendance/regularize'
    | '/attendance/roster'
    | '/attendance/shifts'
    | '/billing-payments/$orgId'
    | '/employees/$id'
    | '/form-16/bulk'
    | '/form-16/management'
    | '/form-16/my'
    | '/holidays/calendar'
    | '/insights/org-tree'
    | '/organizations/$orgId'
    | '/payroll/compliance'
    | '/payroll/import-ctc'
    | '/payroll/run'
    | '/payroll/slips'
    | '/payroll/structure'
    | '/attendance/'
    | '/holidays/'
    | '/payroll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllOffersRoute: typeof AllOffersRoute
  AttendanceRoute: typeof AttendanceRouteWithChildren
  AuthRoute: typeof AuthRoute
  BillingPaymentsRoute: typeof BillingPaymentsRouteWithChildren
  BranchesRoute: typeof BranchesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DesignationsRoute: typeof DesignationsRoute
  EmployeeSeparationRoute: typeof EmployeeSeparationRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  EntitiesRoute: typeof EntitiesRoute
  LeaveRoute: typeof LeaveRoute
  LeaveInboxRoute: typeof LeaveInboxRoute
  LoansRoute: typeof LoansRoute
  ManageRequestsRoute: typeof ManageRequestsRoute
  MyCalendarRoute: typeof MyCalendarRoute
  OfferLettersRoute: typeof OfferLettersRoute
  OfferTemplatesRoute: typeof OfferTemplatesRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  PayrollRoute: typeof PayrollRouteWithChildren
  ReimbursementsRoute: typeof ReimbursementsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminSitesRoute: typeof SuperadminSitesRoute
  Form16BulkRoute: typeof Form16BulkRoute
  Form16ManagementRoute: typeof Form16ManagementRoute
  Form16MyRoute: typeof Form16MyRoute
  HolidaysCalendarRoute: typeof HolidaysCalendarRoute
  InsightsOrgTreeRoute: typeof InsightsOrgTreeRoute
  HolidaysIndexRoute: typeof HolidaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin-sites': {
      id: '/superadmin-sites'
      path: '/superadmin-sites'
      fullPath: '/superadmin-sites'
      preLoaderRoute: typeof SuperadminSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin-dashboard': {
      id: '/superadmin-dashboard'
      path: '/superadmin-dashboard'
      fullPath: '/superadmin-dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursements': {
      id: '/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof ReimbursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-templates': {
      id: '/offer-templates'
      path: '/offer-templates'
      fullPath: '/offer-templates'
      preLoaderRoute: typeof OfferTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-letters': {
      id: '/offer-letters'
      path: '/offer-letters'
      fullPath: '/offer-letters'
      preLoaderRoute: typeof OfferLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-calendar': {
      id: '/my-calendar'
      path: '/my-calendar'
      fullPath: '/my-calendar'
      preLoaderRoute: typeof MyCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-requests': {
      id: '/manage-requests'
      path: '/manage-requests'
      fullPath: '/manage-requests'
      preLoaderRoute: typeof ManageRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-inbox': {
      id: '/leave-inbox'
      path: '/leave-inbox'
      fullPath: '/leave-inbox'
      preLoaderRoute: typeof LeaveInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-separation': {
      id: '/employee-separation'
      path: '/employee-separation'
      fullPath: '/employee-separation'
      preLoaderRoute: typeof EmployeeSeparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designations': {
      id: '/designations'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof DesignationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-payments': {
      id: '/billing-payments'
      path: '/billing-payments'
      fullPath: '/billing-payments'
      preLoaderRoute: typeof BillingPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-offers': {
      id: '/all-offers'
      path: '/all-offers'
      fullPath: '/all-offers'
      preLoaderRoute: typeof AllOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/holidays/': {
      id: '/holidays/'
      path: '/holidays'
      fullPath: '/holidays/'
      preLoaderRoute: typeof HolidaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/payroll/structure': {
      id: '/payroll/structure'
      path: '/structure'
      fullPath: '/payroll/structure'
      preLoaderRoute: typeof PayrollStructureRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/slips': {
      id: '/payroll/slips'
      path: '/slips'
      fullPath: '/payroll/slips'
      preLoaderRoute: typeof PayrollSlipsRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/run': {
      id: '/payroll/run'
      path: '/run'
      fullPath: '/payroll/run'
      preLoaderRoute: typeof PayrollRunRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/import-ctc': {
      id: '/payroll/import-ctc'
      path: '/import-ctc'
      fullPath: '/payroll/import-ctc'
      preLoaderRoute: typeof PayrollImportCtcRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/compliance': {
      id: '/payroll/compliance'
      path: '/compliance'
      fullPath: '/payroll/compliance'
      preLoaderRoute: typeof PayrollComplianceRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/insights/org-tree': {
      id: '/insights/org-tree'
      path: '/insights/org-tree'
      fullPath: '/insights/org-tree'
      preLoaderRoute: typeof InsightsOrgTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays/calendar': {
      id: '/holidays/calendar'
      path: '/holidays/calendar'
      fullPath: '/holidays/calendar'
      preLoaderRoute: typeof HolidaysCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-16/my': {
      id: '/form-16/my'
      path: '/form-16/my'
      fullPath: '/form-16/my'
      preLoaderRoute: typeof Form16MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-16/management': {
      id: '/form-16/management'
      path: '/form-16/management'
      fullPath: '/form-16/management'
      preLoaderRoute: typeof Form16ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-16/bulk': {
      id: '/form-16/bulk'
      path: '/form-16/bulk'
      fullPath: '/form-16/bulk'
      preLoaderRoute: typeof Form16BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/billing-payments/$orgId': {
      id: '/billing-payments/$orgId'
      path: '/$orgId'
      fullPath: '/billing-payments/$orgId'
      preLoaderRoute: typeof BillingPaymentsOrgIdRouteImport
      parentRoute: typeof BillingPaymentsRoute
    }
    '/attendance/shifts': {
      id: '/attendance/shifts'
      path: '/shifts'
      fullPath: '/attendance/shifts'
      preLoaderRoute: typeof AttendanceShiftsRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/roster': {
      id: '/attendance/roster'
      path: '/roster'
      fullPath: '/attendance/roster'
      preLoaderRoute: typeof AttendanceRosterRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/regularize': {
      id: '/attendance/regularize'
      path: '/regularize'
      fullPath: '/attendance/regularize'
      preLoaderRoute: typeof AttendanceRegularizeRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/qr': {
      id: '/attendance/qr'
      path: '/qr'
      fullPath: '/attendance/qr'
      preLoaderRoute: typeof AttendanceQrRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/gps': {
      id: '/attendance/gps'
      path: '/gps'
      fullPath: '/attendance/gps'
      preLoaderRoute: typeof AttendanceGpsRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/face': {
      id: '/attendance/face'
      path: '/face'
      fullPath: '/attendance/face'
      preLoaderRoute: typeof AttendanceFaceRouteImport
      parentRoute: typeof AttendanceRoute
    }
  }
}

interface AttendanceRouteChildren {
  AttendanceFaceRoute: typeof AttendanceFaceRoute
  AttendanceGpsRoute: typeof AttendanceGpsRoute
  AttendanceQrRoute: typeof AttendanceQrRoute
  AttendanceRegularizeRoute: typeof AttendanceRegularizeRoute
  AttendanceRosterRoute: typeof AttendanceRosterRoute
  AttendanceShiftsRoute: typeof AttendanceShiftsRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceFaceRoute: AttendanceFaceRoute,
  AttendanceGpsRoute: AttendanceGpsRoute,
  AttendanceQrRoute: AttendanceQrRoute,
  AttendanceRegularizeRoute: AttendanceRegularizeRoute,
  AttendanceRosterRoute: AttendanceRosterRoute,
  AttendanceShiftsRoute: AttendanceShiftsRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface BillingPaymentsRouteChildren {
  BillingPaymentsOrgIdRoute: typeof BillingPaymentsOrgIdRoute
}

const BillingPaymentsRouteChildren: BillingPaymentsRouteChildren = {
  BillingPaymentsOrgIdRoute: BillingPaymentsOrgIdRoute,
}

const BillingPaymentsRouteWithChildren = BillingPaymentsRoute._addFileChildren(
  BillingPaymentsRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface OrganizationsRouteChildren {
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface PayrollRouteChildren {
  PayrollComplianceRoute: typeof PayrollComplianceRoute
  PayrollImportCtcRoute: typeof PayrollImportCtcRoute
  PayrollRunRoute: typeof PayrollRunRoute
  PayrollSlipsRoute: typeof PayrollSlipsRoute
  PayrollStructureRoute: typeof PayrollStructureRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollComplianceRoute: PayrollComplianceRoute,
  PayrollImportCtcRoute: PayrollImportCtcRoute,
  PayrollRunRoute: PayrollRunRoute,
  PayrollSlipsRoute: PayrollSlipsRoute,
  PayrollStructureRoute: PayrollStructureRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllOffersRoute: AllOffersRoute,
  AttendanceRoute: AttendanceRouteWithChildren,
  AuthRoute: AuthRoute,
  BillingPaymentsRoute: BillingPaymentsRouteWithChildren,
  BranchesRoute: BranchesRoute,
  DepartmentsRoute: DepartmentsRoute,
  DesignationsRoute: DesignationsRoute,
  EmployeeSeparationRoute: EmployeeSeparationRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  EntitiesRoute: EntitiesRoute,
  LeaveRoute: LeaveRoute,
  LeaveInboxRoute: LeaveInboxRoute,
  LoansRoute: LoansRoute,
  ManageRequestsRoute: ManageRequestsRoute,
  MyCalendarRoute: MyCalendarRoute,
  OfferLettersRoute: OfferLettersRoute,
  OfferTemplatesRoute: OfferTemplatesRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  PayrollRoute: PayrollRouteWithChildren,
  ReimbursementsRoute: ReimbursementsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminSitesRoute: SuperadminSitesRoute,
  Form16BulkRoute: Form16BulkRoute,
  Form16ManagementRoute: Form16ManagementRoute,
  Form16MyRoute: Form16MyRoute,
  HolidaysCalendarRoute: HolidaysCalendarRoute,
  InsightsOrgTreeRoute: InsightsOrgTreeRoute,
  HolidaysIndexRoute: HolidaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
